import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ShadeProvider } from "@/context/useShade";
import { CartProvider } from "@/context/useCart";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import ScrollToTop from "@/components/ScrollToTop";

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kiki Shop",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        sizes: "any",
      },
      {
        url: "/icon.png",
        type: "image/png",
        sizes: "32x32",
      },
    ],
    apple: {
      url: "/apple-touch-icon.png",
      sizes: "180x180",
    },
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased font-sans`}>
        <CartProvider>
          <ShadeProvider>
            <>
              <ScrollToTop />
              <div className="flex flex-col min-h-screen bg-white">
                <Navbar />
                <main className="flex-grow w-full">{children}</main>
                <Footer />
              </div>
            </>
          </ShadeProvider>
        </CartProvider>
      </body>
    </html>
  );
}
